In [2]:
import pandas as pd

In [3]:
listings = pd.read_csv('listings.csv')
listings.head()
calendar = pd.read_csv('calendar.csv')
calendar.head()
landmarks = pd.read_csv('Individual_Landmarks.csv')

In [4]:
listings_cleaned = listings.loc[:,['id', 'host_id', 'host_response_time', 'host_response_rate', 'neighbourhood_cleansed', 'latitude', 'longitude', 'accommodates', 'amenities', 'price', 'minimum_nights', 'maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value']]

listings_cleaned.head()

,id,host_id,host_response_time,host_response_rate,neighbourhood_cleansed,latitude,longitude,accommodates,amenities,price,...,maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,2384.0,2613,within an hour,100%,Hyde Park,41.787900,-87.587800,1,"[""Fire extinguisher"", ""Long term stays allowed...",$114.00,...,60,3.0,1125.0,4.99,4.98,4.99,4.99,4.99,4.96,4.94
1,7126.0,17928,within an hour,100%,West Town,41.901660,-87.680210,2,"[""Fire extinguisher"", ""Long term stays allowed...",$92.00,...,60,30.4,1125.0,4.70,4.84,4.56,4.90,4.87,4.89,4.75
2,10945.0,33004,within an hour,93%,Lincoln Park,41.911960,-87.639810,4,"[""Fire extinguisher"", ""Dishes and silverware"",...",$170.00,...,1125,4.0,1125.0,4.65,4.76,4.78,4.82,4.82,4.99,4.65
3,12140.0,46734,NaN,NaN,Lincoln Park,41.923570,-87.649470,3,"[""Fire extinguisher"", ""Free street parking"", ""...",$329.00,...,10,2.0,10.0,4.93,4.67,5.00,5.00,5.00,5.00,4.87
4,24833.0,101521,within a few hours,94%,Lincoln Park,41.925961,-87.656364,3,"[""Fire extinguisher"", ""Long term stays allowed...",$61.00,...,395,32.6,395.0,4.29,4.07,4.00,4.13,4.03,4.90,4.20

In [5]:
calendar_cleaned = calendar.loc[calendar['available']=='f',['listing_id', 'date', 'available', 'price', 'adjusted_price']]
calendar_cleaned.head()

   listing_id       date available     price adjusted_price
0        2384  9/12/2023         f  $125.00        $125.00
1        2384  9/13/2023         f  $125.00        $125.00
2        2384  9/14/2023         f  $125.00        $125.00
3        2384  9/15/2023         f  $100.00        $100.00
4        2384  9/16/2023         f  $100.00        $100.00

In [6]:
landmarks_cleaned = landmarks.loc[:, ['LANDMARK NAME', 'ID', 'LATITUDE','LONGITUDE', 'LOCATION']]
landmarks_cleaned.head()

,LANDMARK NAME,ID,LATITUDE,LONGITUDE,LOCATION
0,Vassar Swiss Underwear Company Building,L-265,41.931627,-87.692100,"(41.9316266084, -87.6921000957)"
1,Mathilde Eliel House,L- 89,41.819256,-87.602788,"(41.819255751, -87.6027879992)"
2,Manhattan Building,L-139,41.876066,-87.628964,"(41.8760657234, -87.6289644505)"
3,Machinery Hall at Illinois Institute of Techno...,L- 12,41.835161,-87.629221,"(41.8351614122, -87.6292212235)"
4,Melissa Ann Elam House,L- 88,41.808530,-87.617204,"(41.808529769, -87.6172043949)"

In [30]:
listings_dropped = listings_cleaned.dropna()
listings_dropped

,id,host_id,host_response_time,host_response_rate,neighbourhood_cleansed,latitude,longitude,accommodates,amenities,price,...,maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,2.384000e+03,2613,within an hour,100%,Hyde Park,41.787900,-87.587800,1,"[""Fire extinguisher"", ""Long term stays allowed...",$114.00,...,60,3.0,1125.0,4.99,4.98,4.99,4.99,4.99,4.96,4.94
1,7.126000e+03,17928,within an hour,100%,West Town,41.901660,-87.680210,2,"[""Fire extinguisher"", ""Long term stays allowed...",$92.00,...,60,30.4,1125.0,4.70,4.84,4.56,4.90,4.87,4.89,4.75
2,1.094500e+04,33004,within an hour,93%,Lincoln Park,41.911960,-87.639810,4,"[""Fire extinguisher"", ""Dishes and silverware"",...",$170.00,...,1125,4.0,1125.0,4.65,4.76,4.78,4.82,4.82,4.99,4.65
4,2.483300e+04,101521,within a few hours,94%,Lincoln Park,41.925961,-87.656364,3,"[""Fire extinguisher"", ""Long term stays allowed...",$61.00,...,395,32.6,395.0,4.29,4.07,4.00,4.13,4.03,4.90,4.20
5,2.587900e+04,101521,within a few hours,94%,Lincoln Park,41.924990,-87.655730,6,"[""Fire extinguisher"", ""Long term stays allowed...",$95.00,...,300,46.7,300.0,4.30,4.57,4.24,4.13,4.13,4.92,4.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8449,9.680970e+17,82950654,within an hour,100%,Austin,41.900071,-87.751783,12,"[""Fire extinguisher"", ""Long term stays allowed...",$299.00,...,365,2.0,365.0,5.00,5.00,5.00,5.00,5.00,5.00,5.00
8455,9.683600e+17,430882859,within a few hours,100%,Uptown,41.955383,-87.649993,3,"[""Fire extinguisher"", ""Long term stays allowed...",$109.00,...,365,2.0,365.0,5.00,5.00,5.00,5.00,5.00,5.00,5.00
8468,9.697680e+17,235678953,within an hour,99%,Near West Side,41.887883,-87.643916,6,"[""Fire extinguisher"", ""Long term stays allowed...",$216.00,...,365,2.0,365.0,3.00,2.00,3.00,4.00,4.00,4.00,2.00
8475,9.703900e+17,17266955,within a few hours,82%,Edgewater,41.988150,-87.673240,2,"[""Fire extinguisher"", ""TV"", ""Wifi"", ""Smoke ala...",$90.00,...,365,2.0,365.0,5.00,5.00,5.00,5.00,5.00,5.00,5.00
8491,9.730150e+17,67751745,within an hour,100%,Near North Side,41.896538,-87.638062,6,"[""Fire extinguisher"", ""Long term stays allowed...",$367.00,...,999,4.8,999.0,5.00,5.00,5.00,5.00,5.00,5.00,5.00

In [27]:
missing_values_listings = listings_cleaned.loc[~listings_cleaned.id.isin(listings_dropped.id), :]
missing_values_listings

,id,host_id,host_response_time,host_response_rate,neighbourhood_cleansed,latitude,longitude,accommodates,amenities,price,...,maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
3,1.214000e+04,46734,NaN,NaN,Lincoln Park,41.923570,-87.649470,3,"[""Fire extinguisher"", ""Free street parking"", ""...",$329.00,...,10,2.0,10.0,4.93,4.67,5.00,5.00,5.00,5.00,4.87
7,3.773800e+04,162364,NaN,NaN,Uptown,41.973030,-87.665670,2,"[""Fire extinguisher"", ""Host greets you"", ""Dish...",$110.00,...,1125,32.0,1125.0,4.99,4.99,5.00,4.99,4.98,4.92,4.98
18,2.503540e+05,1311953,NaN,NaN,Near South Side,41.859230,-87.621980,2,"[""Long term stays allowed"", ""Host greets you"",...",$170.00,...,365,180.0,365.0,4.84,4.94,4.53,4.94,4.97,4.82,4.47
22,2.901550e+05,1505878,NaN,NaN,Bridgeport,41.827120,-87.640460,6,"[""Fire extinguisher"", ""Long term stays allowed...",$130.00,...,90,32.0,1125.0,4.84,4.94,4.62,4.96,5.00,4.72,4.86
23,3.121920e+05,1505878,NaN,NaN,Bridgeport,41.827410,-87.639340,6,"[""Fire extinguisher"", ""Long term stays allowed...",$146.00,...,120,32.0,1125.0,4.74,4.72,4.82,4.95,4.97,4.64,4.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8523,9.769990e+17,11120895,within an hour,100%,Near West Side,41.875333,-87.689492,13,"[""Fire extinguisher"", ""Long term stays allowed...",$438.00,...,365,30.0,365.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8524,9.771450e+17,260588213,within an hour,100%,Mckinley Park,41.825997,-87.669151,1,"[""Fire extinguisher"", ""Long term stays allowed...",$32.00,...,365,2.0,365.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8525,9.777470e+17,536514763,NaN,NaN,West Englewood,41.763133,-87.656318,4,"[""TV"", ""Keypad"", ""Wifi"", ""Self check-in"", ""Sec...",$24.00,...,365,32.0,365.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8526,9.779810e+17,107434423,within an hour,100%,Loop,41.869479,-87.631225,2,"[""Long term stays allowed"", ""Hair dryer"", ""Cof...",$127.00,...,1125,354.1,1125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8527,9.782650e+17,518917937,within an hour,100%,Lake View,41.948470,-87.657230,8,"[""Fire extinguisher"", ""Dishes and silverware"",...",$366.00,...,365,2.0,1125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
calendar_unique = calendar_cleaned.nunique()
calendar_unique

listing_id        2723
date               365
available            1
price             1345
adjusted_price    1349
dtype: int64